title: Test Automation Engineer
email: raulbatalh@gmail.com
description: >- 
  | Teste Automatizado de Software
  | Lider de Qualidade
  | Aprendizado de Máquina |
  > Interessado em como as máquinas compreendem o mundo, aplicando princípios de qualidade de software para garantir que os sistemas sejam eficientes, confiáveis e escaláveis.

author:
  name   : "Raul Batalha"
  avatar : "/assets/images/bio-raul-batalha.jpeg"
  bio    : |
    | Teste Automatizado de Software
    | Lider de Qualidade
    | Aprendizado de Máquina |
    > Interessado em como as máquinas compreendem o mundo, aplicando princípios de qualidade de software para garantir que os sistemas sejam eficientes, confiáveis e escaláveis.
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/raulbatalha"
    
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/raulbatalha/"

    - label: "WhatsApp"
      icon: "fab fa-fw fa-whatsapp"
      url: "https://wa.me/5592981238353"
    
    - label: "Skype"
      icon: "fab fa-fw fa-skype"
      url: "skype:raulbatalha?chat"
    
    - label: "E-mail"
      icon: "fas fa-fw fa-envelope"
      url: "mailto:raul.batalha@hotmail.com"

twitter_username: raulbatalha
github_username: raulbatalha
minimal_mistakes_skin: air
search: true

markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
permalink: /:categories/:title/
paginate: 5
paginate_path: /page:num/
timezone:

include:
  - _pages

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/raulbatalha"
    
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/raulbatalha/"

    - label: "WhatsApp"
      icon: "fab fa-fw fa-whatsapp"
      url: "https://wa.me/5592981238353"

    - label: "Skype"
      icon: "fab fa-fw fa-skype"
      url: "skype:raulbatalha?chat"
    
    - label: "E-mail"
      icon: "fas fa-fw fa-envelope"
      url: "mailto:raul.batalha@hotmail.com"

collections:
  portfolio:
    output: true
    permalink: /:collection/:path/

markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: false
      read_time: true
      comments: true
      share: true
      related: true
      classes: wide

  - scope:
      path: "_pages"
      type: pages
    values:
      layout: archive
      author_profile: true

  - scope:
      path: ""
      type: portfolio
    values:
      layout: archive
      author_profile: true
      share: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/